/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddNote {
        /**
          * The first name
         */
        "handleAddNote": any;
    }
    interface NotesComponent {
        /**
          * The last name
         */
        "date": any;
        "handleDelete": any;
        /**
          * The middle name
         */
        "text": string;
    }
    interface NotesDashboard {
    }
    interface NotesList {
        /**
          * The middle name
         */
        "handleAddNote": string;
        /**
          * The last name
         */
        "handleDelete": any;
        /**
          * The first name
         */
        "notes": any;
    }
}
declare global {
    interface HTMLAddNoteElement extends Components.AddNote, HTMLStencilElement {
    }
    var HTMLAddNoteElement: {
        prototype: HTMLAddNoteElement;
        new (): HTMLAddNoteElement;
    };
    interface HTMLNotesComponentElement extends Components.NotesComponent, HTMLStencilElement {
    }
    var HTMLNotesComponentElement: {
        prototype: HTMLNotesComponentElement;
        new (): HTMLNotesComponentElement;
    };
    interface HTMLNotesDashboardElement extends Components.NotesDashboard, HTMLStencilElement {
    }
    var HTMLNotesDashboardElement: {
        prototype: HTMLNotesDashboardElement;
        new (): HTMLNotesDashboardElement;
    };
    interface HTMLNotesListElement extends Components.NotesList, HTMLStencilElement {
    }
    var HTMLNotesListElement: {
        prototype: HTMLNotesListElement;
        new (): HTMLNotesListElement;
    };
    interface HTMLElementTagNameMap {
        "add-note": HTMLAddNoteElement;
        "notes-component": HTMLNotesComponentElement;
        "notes-dashboard": HTMLNotesDashboardElement;
        "notes-list": HTMLNotesListElement;
    }
}
declare namespace LocalJSX {
    interface AddNote {
        /**
          * The first name
         */
        "handleAddNote"?: any;
    }
    interface NotesComponent {
        /**
          * The last name
         */
        "date"?: any;
        "handleDelete"?: any;
        /**
          * The middle name
         */
        "text"?: string;
    }
    interface NotesDashboard {
    }
    interface NotesList {
        /**
          * The middle name
         */
        "handleAddNote"?: string;
        /**
          * The last name
         */
        "handleDelete"?: any;
        /**
          * The first name
         */
        "notes"?: any;
    }
    interface IntrinsicElements {
        "add-note": AddNote;
        "notes-component": NotesComponent;
        "notes-dashboard": NotesDashboard;
        "notes-list": NotesList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-note": LocalJSX.AddNote & JSXBase.HTMLAttributes<HTMLAddNoteElement>;
            "notes-component": LocalJSX.NotesComponent & JSXBase.HTMLAttributes<HTMLNotesComponentElement>;
            "notes-dashboard": LocalJSX.NotesDashboard & JSXBase.HTMLAttributes<HTMLNotesDashboardElement>;
            "notes-list": LocalJSX.NotesList & JSXBase.HTMLAttributes<HTMLNotesListElement>;
        }
    }
}
